In [1]:
import os
import pathlib
from glob import glob

import earthpy
import earthpy.api.appeears as eaapp

import geopandas as gpd
import hvplot.pandas
import hvplot.xarray

import pandas as pd

import rioxarray as rxr
import xarray as xr

import holoviews as hv

from shapely.geometry import Point

In [2]:
lat = 39.631111
lon = -79.957199

study_point = Point(lon, lat)

study_area = gpd.GeoDataFrame(
    {
        "Site": ["West Virginia Site"]
    },
    geometry=[study_point],
    crs="EPSG:4326"
)

study_area

                 Site                   geometry
0  West Virginia Site  POINT (-79.9572 39.63111)

In [3]:
study_area = study_area.to_crs(3857)

study_area["geometry"] = study_area.buffer(500)

study_area = study_area.to_crs(4326)

study_area

                 Site                                           geometry
0  West Virginia Site  POLYGON ((-79.95271 39.63111, -79.95273 39.630...

In [4]:
study_area.hvplot(
    geo=True,
    tiles="OSM",
    alpha=0.4,
    line_color="red",
    width=700,
    height=500,
    title="West Virginia Study Area")

:Overlay
   .WMTS.I     :WMTS   [Longitude,Latitude]
   .Polygons.I :Polygons   [Longitude,Latitude]

In [5]:
project = earthpy.Project("West Virginia NDVI")

download_key = "wv_ndvi"

In [7]:
ndvi_downloader = eaapp.AppeearsDownloader(
    download_key="wv_ndvi",
    project=project,
    product="MOD13Q1.061",
    layer="_250m_16_days_NDVI",
    start_date="05-01",
    end_date="05-31",
    recurring=True,
    year_range=[2017, 2025],   # Adjust if your event year differs
    polygon=study_area
)

In [8]:
ndvi_downloader.download_files(cache=True)

No stored credentials found for urs.earthdata.nasa.gov. Please log in.

/opt/conda/lib/python3.11/site-packages/earthpy/api/auth.py:192: UserWarning: Setting credentials not supported for 'netrc' backend.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/earthpy/api/auth.py:196: UserWarning: Failed to store credentials with 'keyring': No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
  warnings.warn(

Credentials stored using 'env' backend.